---
title: "Data QC Visualizations"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
  font_family: "Roboto"
  google_fonts: true
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.width=15, fig.height=10)
library(tidyverse)
library(lubridate)
library(plotly)
library(SRJPEdata)
library(knitr)
root.dir <- rprojroot::find_rstudio_root_file()
knitr::opts_knit$set(root.dir, fig.width=12, fig.height=8)

colors_small <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                   "#899DA4", "#C93312", "#DC863B" # royal 1 (- 3)
)
colors_full <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                  "#899DA4", "#C93312", "#DC863B", # royal 1 (- 3)
                  "#F1BB7B", "#FD6467", "#5B1A18", "#D67236",# Grand Budapest 1 (-4)
                  "#D8B70A", "#02401B", "#A2A475", # Cavalcanti 1
                  "#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4", #Grand Budapest 2
                  "#9986A5", "#EAD3BF", "#AA9486", "#B6854D", "#798E87", # Isle of dogs 2 altered slightly
                  "#F3DF6C", "#CEAB07", "#D5D5D3", "#24281A", # Moonriese 1, 
                  "#798E87", "#C27D38", "#CCC591", "#29211F", # moonrise 2
                  "#85D4E3", "#F4B5BD", "#9C964A", "#CDC08C", "#FAD77B" # moonrise 3 
)

# Objects to check
# weekly_juvenile_abundance_catch_data
# weekly_juvenile_abundance_efficiency_data
# observed_adult_inputs
# stock_recruit_covariates
```

```{r, include = F}
btspas_catch <- SRJPEdata::weekly_juvenile_abundance_catch_data 
btspas_efficiency <- SRJPEdata::weekly_juvenile_abundance_efficiency_data
adult <- SRJPEdata::observed_adult_input
covariates <- SRJPEdata::stock_recruit_covariates

```

# `weekly_juvenile_abundance_catch_data` {data-orientation="rows"}

## Row {data-height="50"}

```{r, echo = F, message = F, warning = F}
selectInput(
  "plot_filter",
  label = tags$strong("Select Plot Type:"),
  choices = c("missing weeks","raw count","percent cumulative catch curve","absolute cumulative catch curve", "flow"),
  selected = "raw count"
)
selectInput(
  "stream_filter",
  label = tags$strong("Filter by Stream:"),
  choices = c(unique(btspas_catch$stream)),
  selected = "battle creek"
)
selectInput(
  "lifestage_filter",
  label = tags$strong("Filter by Lifestage:"),
  choices = c(unique(btspas_catch$life_stage)),
  selected = "fry"
)
```

```{r, include = F}
# reactive data ################################################################
btspas_cumul <- reactive({
  btspas_catch |> 
  mutate(
    date = lubridate::ymd(paste0(year, '-01-01')) + lubridate::weeks(week - 1),
    water_year = ifelse(month(date) %in% 10:12, year(date) + 1, year(date)),
    fake_date = as_date(paste(
      ifelse(month(date) %in% 10:12, 1999, 2000), month(date), day(date)
    ))
  ) %>%
  arrange(date) %>%
  group_by(stream, water_year, life_stage) %>%
  mutate(
    count = ifelse(is.na(count), 0, count),
    total_count = sum(count, na.rm = T),
    cumulative_catch = cumsum(count),
    prop_cuml_catch = cumulative_catch / total_count * 100
  ) |> 
  filter(stream %in% input$stream_filter,
         life_stage %in% input$lifestage_filter)
  })

missing_weeks <- reactive({
  btspas_catch |> 
  filter(is.na(count), week %in% c(seq(45, 53), seq(1, 22))) |> 
  distinct(run_year, stream, site, week) |> 
  group_by(run_year, stream, site) |> 
  tally() |> 
  filter(stream %in% input$stream_filter)
  })

flow <- reactive({
  btspas_catch |> 
    mutate(
    date = lubridate::ymd(paste0(year, '-01-01')) + lubridate::weeks(week - 1),
    water_year = ifelse(month(date) %in% 10:12, year(date) + 1, year(date)),
    fake_date = as_date(paste(
      ifelse(month(date) %in% 10:12, 1999, 2000), month(date), day(date)
    )),
    run_year = as.factor(run_year)) |> 
    distinct(year, run_year, fake_date, stream, site, flow_cfs, standardized_flow) |> 
    filter(stream %in% input$stream_filter)
})

# plots #######################################################################
# number of missing weeks by stream, site, year, lifestage
# filter by stream
missing_weeks_plot <- reactive(missing_weeks() |> 
    plot_ly(
    x = ~ run_year,
    y = ~ n,
    color = ~ site,
    text = ~ run_year,
    hovertemplate = paste("RunYear: %{text}"),
    colors = colors_small,
    type = 'bar'
  ) %>%
  layout(
    title = "Missing Weeks",
    xaxis = list(title = "Months", tickformat = "%b"),
    yaxis = list(title = "Number of missing weeks")
  ))                        

flow_plot <- reactive(flow() |> 
    plot_ly(
    x = ~ fake_date,
    y = ~ flow_cfs,
    color = ~ run_year,
    text = ~ site,
    hovertemplate = paste("Run Year: %{text}"),
    colors = colors_small,
    type = 'scatter',
    mode = 'markers'
  ) %>%
  layout(
    title = "Flow (cfs)",
    xaxis = list(title = "Months", tickformat = "%b"),
    yaxis = list(title = "Flow (cfs)")
  ))      

#### raw count
 raw_count <- reactive(btspas_cumul() |>
  plot_ly(
    x = ~ fake_date,
    y = ~ count,
    color = ~ site,
    text = ~ water_year,
    hovertemplate = paste("Water Year: %{text}"),
    colors = colors_small,
    type = 'scatter',
    mode = 'markers'
  ) %>%
  layout(
    title = "Raw Catch in RST",
    xaxis = list(title = "Months", tickformat = "%b"),
    yaxis = list(title = "Raw Catch")
  ))

#### percent cumulative catch curve

 percent_cumulative <- reactive(btspas_cumul() |>
  plot_ly(
    x = ~ fake_date,
    y = ~ prop_cuml_catch,
    color = ~ site,
    text = ~ water_year,
    hovertemplate = paste("Water Year: %{text}"),
    colors = colors_small,
    type = 'scatter',
    mode = 'lines'
  ) %>%
  layout(
    title = "Cumulative Catch in RST",
    xaxis = list(title = "Months", tickformat = "%b"),
    yaxis = list(title = "Percent Cumulative Catch")
  ))

#### absolute cumulative catch curve
 
absolute_cumulative <- reactive(btspas_cumul() |>
  plot_ly(
    x = ~ fake_date,
    y = ~ cumulative_catch,
    color = ~ site,
    text = ~ water_year,
    hovertemplate = paste("Water Year: %{text}"),
    colors = colors_small,
    type = 'scatter',
    mode = 'lines'
  ) %>%
  layout(
    title = "Cumulative Catch in RST",
    xaxis = list(title = "Months", tickformat = "%b"),
    yaxis = list(title = "Absolute Cumulative Catch")
  ))
```

## Row

```{r, echo = F, message = F, warning = F}

plot <- reactive({
  if(input$plot_filter == "missing weeks"){
  missing_weeks_plot()
  } else if(input$plot_filter == "flow") {
  flow_plot()
} else if(input$plot_filter == "raw count") {
  raw_count()
} else if(input$plot_filter == "percent cumulative catch curve") {
  percent_cumulative()
} else if(input$plot_filter == "absolute cumulative catch curve") {
  absolute_cumulative()
}
})

renderPlotly(plot())
```

# `weekly_juvenile_abundance_efficiency_data` {data-orientation="rows"}

## Row {data-height="50"}

```{r, echo = F, message = F, warning = F}
selectInput(
  "plot_filter2",
  label = tags$strong("Select Plot Type:"),
  choices = c("efficiency"),
  selected = "efficiency"
)
selectInput(
  "stream_filter2",
  label = tags$strong("Filter by Stream:"),
  choices = c(unique(btspas_catch$stream)),
  selected = "battle creek"
)
sliderInput(
  "year_filter2",
  label = tags$strong("Filter by Year:"),
  min = 1996,
  max = 2024,
  value = c(1996,2024))
```

```{r, include = F}
btspas_eff_filter <- reactive({
  btspas_efficiency |> 
    filter(stream %in% input$stream_filter2,
         ((run_year >= input$year_filter2[1] & run_year <= input$year_filter2[2]) | run_year ==  input$year_filter2[1])) |>
    mutate(
    date = lubridate::ymd(paste0(year, '-01-01')) + lubridate::weeks(week - 1),
    fake_date = as_date(paste(
      ifelse(month(date) %in% 10:12, 1999, 2000), month(date), day(date)
    ))) |> 
    ungroup() |> 
    group_by(stream, fake_date) |> 
    summarize(number_released = sum(number_released, na.rm = T),
              number_recaptured = sum(number_recaptured, na.rm = T))
  
})
```

```{r, include = F}
efficiency_plot <- reactive(
  btspas_eff_filter() |>
    plot_ly(x = ~ fake_date,
            y = ~ number_released,
            type = "bar",
            name = "number released",
            marker = list(color = "#9A8822")) |> 
    add_trace(y = ~ number_recaptured,
              name = "number_recaptured",
              marker = list(color = "#899DA4")) |> 
    layout(xaxis = list(title = "Months", tickformat = "%b%d"),
           barmode = 'stack')
)
                         
```

## Row

```{r, echo = F, message = F, warning = F}

plot2 <- reactive({
  if(input$plot_filter2 == "efficiency"){
  efficiency_plot()
  }
})

renderPlotly(plot2())
```

# `observed_adult_input` {data-orientation="rows"}

## Row {data-height="50"}

```{r, echo = F, message = F, warning = F}
selectInput(
  "plot_filter3",
  label = tags$strong("Select Plot Type:"),
  choices = c("adult counts"),
  selected = "adult counts"
)
selectInput(
  "stream_filter3",
  label = tags$strong("Filter by Stream:"),
  choices = c(unique(adult$stream)),
  selected = "battle creek"
)
```

```{r, include = F}
adult_filter <- reactive({
  adult |> 
    pivot_wider(id_cols = c(year, stream), names_from = "data_type", values_from = "count") |> 
    filter(stream %in% input$stream_filter3) 
})

adult_plot <- reactive(adult_filter() |> 
  plot_ly(x = ~ year,
          y = ~ upstream_estimate, 
          type = "bar",
          name = "upstream estimate",
          marker = list(color = "#9A8822")) |> 
    add_trace(y = ~ redd_count,
              name = "redd count",
              marker = list(color = "#899DA4")) |> 
   add_trace(y = ~ holding_count,
              name = "holding count",
              marker = list(color = "#F8AFA8")) |> 
   add_trace(y = ~ carcass_estimate,
              name = "carcass estimate",
              marker = list(color = "#DC863B"))
  )
```

## Row

```{r, echo = F, message = F, warning = F}

plot3 <- reactive({
  if(input$plot_filter3 == "adult counts"){
  adult_plot()
  }
})

renderPlotly(plot3())
```
